name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Prepare build environment
        uses: ./.github/actions/setup-lf-env
      # - name: Setup Scala
      #   uses: olafurpg/setup-scala@v10
      #   with:
      #     java-version: adopt@1.8
      # - name: Cache Scala
      #   uses: coursier/cache-action@v5
      - name: Unit tests
        run: make test
      - name: Check out lingua-franca repository
        uses: actions/checkout@v3
        with:
          repository: erlingrj/lingua-franca
          submodules: true
          ref: chisel3
          fetch-depth: 0
      - name: Check out specific ref of reactor-chisel
        uses: actions/checkout@v3
        with:
          repository: erlingrj/reactor-chisel
          path: core/src/main/resources/lib/chisel/reactor-chisel
          ref: ${{ github.ref }}
      - name: Install verilator
        run: sudo apt install verilator
      - name: Run Chisel tests;
        run: |
          ./gradlew targetTest -Ptarget=Chisel
      